### ISSUE TITLE
不知道为啥要 require React

### ISSUE THREAD

**Issue by afc163** [react-component/upload#1]

**Comment by shepherdwind** [comment]
如果不用兼容ie，就不需要。

如果兼容ie，必须把input=file覆盖到上传按钮上吧，不用React也可以实现，但是用起来就不那么方便了。

**Comment by shepherdwind** [comment]
如果不用React，就需要这样写了

```
var a = React.render(<a href="#nowhere">上传文件</a>);
props.el = React.findDOMNode(a);
new Upload(props);
```

这样其实也行，就是upload里面需要自己操作dom了。另外如果直接不依赖React，就可以省略没有用的span那一层包裹了。

**Comment by shepherdwind** [comment]
我现在疑惑的是，是否有必要不依赖React，这个组件有必要支持没有React的场景么？

**Comment by afc163** [comment]
嗯，这样也方便些。
