### ISSUE TITLE
How to encode file name before uploading?

### ISSUE THREAD

**Issue by sivadass** [react-component/upload#116]
Huge thanks for making this component first :)

The upload component just works fine.

Now I have to encode the URL of the file before getting uploaded to the server, in order to replace `space characters` from file name with `%20` string.

I am aware that we can achieve the same using encodeURIComponent

Can anybody help me to achieve the same in **antd-design**'s upload component.

**Comment by yesmeck** [comment]
```javascript
<Upload data={(file) => file.name = 'foo'} />
```

**Comment by sivadass** [comment]
Will it work like this `<Upload data={(file) => file.name = encodeURIComponent(file.name)} />` ?

**Comment by yesmeck** [comment]
yes

**Comment by sivadass** [comment]
Am getting 

> Cannot assign to read only property 'name' of object '#<File>'

Codesandbox link [here](https://2p6rp6p0qn.codesandbox.io/).

**Comment by iamppz** [comment]
Same issue.
