### ISSUE TITLE
Unknown props `directory`, `webkitdirectory` on <input> tag

### ISSUE THREAD

**Issue by zetekla** [react-component/upload#124]
https://github.com/react-component/upload/commit/7d5e9cf62818a55209b9215ff5ab1023170edc16#diff-6adaad797d2e834d256c2627b443d2dbR214

warning.js:33 Warning: Unknown props `directory`, `webkitdirectory` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by AjaxUploader)
    in span (created by AjaxUploader)
    in AjaxUploader (created by Upload)
    in Upload (created by ImportExperiment)
    in div (created by ImportExperiment)
    in div (created by ModalBody)
    in ModalBody (created by ModalBox)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in ModalDialog (created by Modal)
    in Transition (created by Fade)
    in Fade (created by Modal)
    in div (created by Modal)

**Comment by afc163** [comment]
Try react@16.5
