### ISSUE TITLE
Add openFileDialogOnEnter

### ISSUE THREAD

**Issue by DavidSichau** [react-component/upload#135]
Hi thanks for the library.

I tried to use the library for drag and drop upload inside around an editor component.

The problem is that the library opens the fileUploadDialog every time one presses enter in the editor component.

I therefore suggest that similar to `openFileDialogOnClick` and `openFileDialogOnEnter` prop is added, with which one can disable the on key event listener.

This would allow one to use the library for only drag and drop events.

**Comment by afc163** [comment]
https://github.com/react-component/upload/pull/125
