### ISSUE TITLE
父页面设置了 document.domain 时报错

### ISSUE THREAD

**Issue by afc163** [react-component/upload#14]
rc-upload@1.6.0

**Comment by afc163** [comment]
http://www.jiancool.com/article/38902234973/

**Comment by afc163** [comment]
https://github.com/react-component/upload/tree/fix-cross-domain

修改了 domain 后可以写入内容。但是 submit 后，貌似又会改变 domain 导致获取 response 失败。难搞。

**Comment by afc163** [comment]
这个一直有问题，@yiminghe 看下？

**Comment by yiminghe** [comment]
doc updated

```js
var ret = '';
if(postData._documentDomain){
  ret+='<script>document.domain="'+postData._documentDomain+'";</script>'
}
this.body = ret +'{"url":"xx.jpq"}';
```

**Comment by yiminghe** [comment]
https://github.com/react-component/upload/commit/61ac4c955ff8085a6defc57c6b81a6b56dc35f9f
