### ISSUE TITLE
选择文件后如何阻止文件上传

### ISSUE THREAD

**Issue by stonelee** [react-component/upload#17]
在上传之前，有时候需要对已选择的文件进行校验，例如大小、类型等等。
目前可以在onStart中进行校验，但是校验失败时，无法阻止上传请求的发送。

**Comment by yiminghe** [comment]
en , pull request 个吧，如果 onStart  return false 就终止

**Comment by stonelee** [comment]
我的具体业务场景还没那么简单呢，校验是异步的，简单的return false还不行，恐怕得把request.post放出来，让业务上自己调用才好。

目前我的做法是在onStart中返回一个promise，校验成功就resolve，校验失败就reject
。然后在onSuccess跟onError中进行判断，成功时才回填上传文件的id。缺点就是前端校验失败也会触发上传，但是满足业务需要了~

**Comment by afc163** [comment]
前端校验为啥需要异步？

**Comment by stonelee** [comment]
![image](https://cloud.githubusercontent.com/assets/571863/10045916/804d71da-6238-11e5-840c-f28c08be6659.png)
校验图片大小~

**Comment by stonelee** [comment]
校验图片大小~

![image](https://cloud.githubusercontent.com/assets/571863/10045980/de426b06-6238-11e5-994a-2c4349ef05be.png)

**Comment by shepherdwind** [comment]
这个感觉只能支持高级浏览器了吧

**Comment by stonelee** [comment]
嗯哪，我的业务场景只需要高级浏览器即可。各位看下需不需要这种情况的支持
