### ISSUE TITLE
JWT support?

### ISSUE THREAD

**Issue by mydearxym** [react-component/upload#22]
请问一下 upload 组件在 post 时候怎样在添加 headers 里面加入token 信息呢？

比如：
```js
Authorization: Bearer .....
```

**Comment by yiminghe** [comment]
需要增加 headers 设置

**Comment by yiminghe** [comment]
欢迎 pr

**Comment by shepherdwind** [comment]
https://github.com/react-component/upload/blob/master/src/request.js#L59 这里写头信息的，不过应该只能在 ajax 里面加，ie 就算了。

**Comment by mydearxym** [comment]
谢谢回复  
既然 XMLHttpRequest 的兼容性这么差，是否可以考虑换一个成熟的 ajax ?
<img alt="logo" title="c" src="https://git.oschina.net/mydearxym2/assets_server/raw/master/__tmp_issue.png" />

**Comment by shepherdwind** [comment]
图片上传，用普通的 ajax 不行，ie 需要用 iframe，不能自定义 header 的

**Comment by mydearxym** [comment]
这块不太了解， 谢谢科普

**Comment by afc163** [comment]
感觉可以给高级浏览器加上 header 支持。

**Comment by tamert** [comment]
i have a problem, i want this;
`headers={{Authorization: `Bearer ${token}`}}` is possible?
