### ISSUE TITLE
ie8下，服务器端应该返回怎么样的结果

### ISSUE THREAD

**Issue by wp2123** [react-component/upload#24]
我在做ie8下的调试，但是不是很明白你们提供的IE8/9的Note的意思。
项目后端用的nodejs，目前返回的结果是
```
    <script>document.domain="localhost"</script>  + {} //发送过来的数据中好像没有domain，我这里返回“”或者null也都不可以
```
前端会提醒返回document.domain的script标签，并且显示拒绝访问。
后端返回的数据有问题吗
谢谢

**Comment by shepherdwind** [comment]
https://github.com/react-component/upload/blob/master/server-fn.js#L25 参考这个吧

**Comment by wp2123** [comment]
首先多谢提供的这个参考。
我后端用的是express，上传的方法大概是这样的

```
var form = new formidable.IncomingForm();
form.parse(req, function (err, fields, files) {
  var ret = '';
  res.status(200);
  res.set('Content-Type', 'text/html');
  if (fields['_documentDomain']) {
    ret += '<script>document.domain="' + fields['_documentDomain'] + '";</script>';
  }
  ret += JSON.stringify(response);
  res.send(ret).end();
}
```

不知道是不是我哪里写错了，但是即使这样ie8也还是会报出“拒绝访问”的错误。

**Comment by afc163** [comment]
你客户端设置了 domain 么？

_documentDomain 是什么？

一般情况下不需要配置这个。

**Comment by wp2123** [comment]
客户端没有设置，服务端收到的数据有的时候_documentDomain=localhost，有的时候没有这个值

**Comment by afc163** [comment]
客户端没有设置的时候，不需要传 _documentDomain 到后台。

**Comment by wp2123** [comment]
我没有特意往数据里加这个值，都是rc-upload来控制的。
是不是说如果_documentDomain为空的话，后端不需要返回document.domain的script标签了？
去试过不返回这个标签，但是也有拒绝访问的错误。
我通过在你们的代码中打印log，看到第一次initIframe的时候，domain是空的。上传完成之后，domain是localhost，不知道是不是这里的问题。
我再继续调试一下

**Comment by afc163** [comment]
> 是不是说如果_documentDomain为空的话，后端不需要返回document.domain的script标签了？

对的。

**Comment by wp2123** [comment]
是不是我太笨了，还是没有调试出来...

我客户端没有设置documentDomain，上传接口是跨域的操作，返回结果里边不管有没有document.domain的script标签都显示拒绝访问...

真是麻烦你们了，我再看看，不行就用别的插件了...

**Comment by shepherdwind** [comment]
@afc163 看看吧，我已经木有 ie8 了，还要兼容 ie 简直就是悲剧啊

**Comment by afc163** [comment]
http://f2etest.alibaba-inc.com/
