### ISSUE TITLE
3.1.2 是个空包

### ISSUE THREAD

**Issue by hhking** [react-component/upload#256]
antd 安装完后，发现 `rc-upload` not found，发现这个依赖是空包

![image](https://user-images.githubusercontent.com/11470599/83473346-eb324000-a4bb-11ea-952b-1c919994ad11.png)

**Comment by yoyo837** [comment]
@afc163 @zombieJ 加急修复一下发布

**Comment by zombieJ** [comment]
嗯，发了 3.1.3
