### ISSUE TITLE
上传文件带cookie

### ISSUE THREAD

**Issue by Alexoner** [react-component/upload#26]
如题，上传时没有带cookie，导致需要登录的应用在上传的时候无法成功。可否加上在请求中加上credential.

经过测试request.js中加上
```javascript
  xhr.withCredentials = true;
```
就可以

**Comment by shepherdwind** [comment]
来一个mr呗

**Comment by Alexoner** [comment]
已经pull request，但是ci貌似有些问题，帮忙处理一下吧。https://github.com/react-component/upload/pull/27
