### ISSUE TITLE
需要拖拽同时支持上传文件夹和文件上传。

### ISSUE THREAD

**Issue by 4-1-1** [react-component/upload#305]
~~现在文件夹上传模式下，不能选择单文件上传，这个是浏览器不支持， 所以这个方案也不考虑~~

但是使用多文件上传模式时，拖拽文件夹不能识别文件夹的内容，我看其他组件是支持的，所以是不是可以加参数支持一下

**Comment by afc163** [comment]
https://codesandbox.io/s/tuozhuaishangchuan-antd4140-forked-opx6d?file=/index.js
