### ISSUE TITLE
Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by MarshallChen** [react-component/upload#33]
在跨域上传时出现的错误，发现来自这一行，这里是不是要做判断？

```javascript
xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
```

https://github.com/react-component/upload/blob/master/src/request.js#L68

**Comment by shepherdwind** [comment]
这个头可以自己改掉的

**Comment by shepherdwind** [comment]
@MarshallChen 你可以提一个 mr ，如果配置了 headers['X-Requested-With'] = null ，就关闭这个设置。

**Comment by Robot-L** [comment]
在上传组件中如下设置即可
```js
headers: {
   'X-Requested-With':null
  },
```
为后面的小伙伴们解惑(星星脸)

**Comment by minwe** [comment]
使用 CORS 跨域上传时，监听 `xhr.upload` 相关事件（如 `xhr.upload.onprogress`）也会触发 OPTIONS 请求：

```javascript
    xhr.upload.onprogress = function progress(e) {
      if (e.total > 0) {
        e.percent = e.loaded / e.total * 100;
      }
      option.onProgress(e);
    };
```

https://github.com/react-component/upload/blob/eac29ade40fd03c35ecbbc6f72ad070250b5ddff/src/request.js#L37-L43

由于 OPTIONS 是不带 cookie 的，像 Sofa 这种框架，如果 CORS  相关 HEADER 设置在 Java 代码里，OPTIONS 会被拦截到登录页面，导致请求失败。

两种处理方式：

1. 将 CORS 相关 HEADER 设置在 Web 服务器配置上（如 Apache、Nginx）；
2. 移除 `xhr.upload.onprogress` 相关代码，只有在用户显示设置相关选项时才去监听这个事件，避免不需要监听的这个事件的用户触发 OPTIONS 请求。

个人目前的处理方式是本地存了一份修改版的 Upload 组件，删除了监听进度相关代码（后端不太配合把 CORS 配置移到 Apache 上）。

**Comment by shepherdwind** [comment]
@minwe 这个可以改下吧，可以加一个配置关闭这个功能，欢迎 pr 。

**Comment by minwe** [comment]
@shepherdwind 在 antd 里添加了一个属性，已经 PR

**Comment by ChhXin** [comment]
> 在上传组件中如下设置即可
> 
> ```js
> headers: {
>    'X-Requested-With':null
>   },
> ```
> 
> 为后面的小伙伴们解惑(星星脸)

有个疑问不好意思，这个参数不是同步异步吗？跟跨域有关系？为啥设置了同步就不跨域了

**Comment by Ha0ran2001** [comment]
> > 在上传组件中如下设置即可
> > ```js
> > headers: {
> >    'X-Requested-With':null
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为后面的小伙伴们解惑(星星脸)
> 
> 有个疑问不好意思，这个参数不是同步异步吗？跟跨域有关系？为啥设置了同步就不跨域了

同问

**Comment by minwe** [comment]
@xinchanghao @Ha0ran2001 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS#%E8%8B%A5%E5%B9%B2%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E5%9C%BA%E6%99%AF

`X-Requested-With` 是自定义的请求头，POST 请求 + 自定义请求头会触发 CORS 预检。
