### ISSUE TITLE
Can not get ref inside Upload

### ISSUE THREAD

**Issue by afc163** [react-component/upload#36]
```jsx
<Upload>
  <input ref="xx" />   // can not get this refs when componentDidMount
</Upload>
```

https://github.com/react-component/upload/blob/9b5b6e13888a042b51ff4b42ac175a76f5426f17/src/Upload.jsx#L58

**Comment by yiminghe** [comment]
https://github.com/react-component/upload/commit/e6dac5bdd78708a170c45b036eaafb9533ed4f2b

**Comment by shepherdwind** [comment]
upload 干嘛还放一个 ref 啊好奇怪。
