### ISSUE TITLE
I couldn't find out how to limit the file size

### ISSUE THREAD

**Issue by jasonji** [react-component/upload#43]
I couldn't find out how to limit the file size

**Comment by shepherdwind** [comment]
You should try [beforeUpload](https://github.com/react-component/upload#props)

**Comment by YashGulati** [comment]
what should be written here to cancel the process?
beforeUpload(file) {
        console.log('beforeUpload', file.name);
        console.log('beforeUpload', file);
        if (file.size > 10485760){
          console.log('greater than 10mb');
          // here must be something which cancels the entire upload process.
          return;
        }
        console.log('nice file size');
      }

**Comment by shepherdwind** [comment]
If the beforeUpload  return false or a rejected Promise will stop upload.

**Comment by YashGulati** [comment]
Thanks founded it already...
beforeUpload(file) {
        if (file.size > 10485760){
          console.log('greater than 10mb');
          return new Promise(function (resolve) {
            console.log('file size exceeds');
          });
        }
        console.log('nice file size');
      }

**Comment by czhaoli** [comment]
but ie9 Can't limit file size
