### ISSUE TITLE
upload上传文件携带cookie的问题

### ISSUE THREAD

**Issue by JoeBBChen** [react-component/upload#44]
### XMLHttpRequest可以在跨域请求时发送认证信息，但在默认情况下HTTP Cookies和HTTP 认证是不被发送的。要发送Preflighted 认证请求需要设置XMLHttpRequest对象的withCredentials属性。
我到源码改了withCredentials属性为true，这时候请求头才会携带cookie，当请求头没有cookie的时候，后台返回的是不在线状态
![image](https://cloud.githubusercontent.com/assets/12586787/16984194/4ffd8456-4eab-11e6-86b6-d75c9183ff05.png)

**Comment by JoeBBChen** [comment]
来这里提了个issue顺便看了一下README，发现已经有withCredentials属性了，但是那个AntDesign那个官网上好像没有提到这个属性

**Comment by afc163** [comment]
来个 PR 如何？

**Comment by JoeBBChen** [comment]
@afc163 还没提过PR :see_no_evil:
