### ISSUE TITLE
拖拽上传含有多个文件的文件夹时，beforeUpload无法获取全部文件，点击上传时可以，这是bug吗？

### ISSUE THREAD

**Issue by boluo-O** [react-component/upload#453]
### 沙盒链接
https://codesandbox.io/s/great-sutherland-6l9jo0?file=/App.tsx:348-360
### 复现步骤
![@Z_`7H)}I3% UOY )YYK5_I](https://user-images.githubusercontent.com/32573416/194806398-e22f1c12-0b8c-41a9-a7a2-e7d319a3b40b.png)

拖拽上传一个有多个文件的文件夹 log 如图 
![_CK79XAV`XIC9H0TLDY R%L](https://user-images.githubusercontent.com/32573416/194806806-830b4938-22b4-402c-89b3-eccff2375de9.png)

点击上传一个有多个文件的文件夹 log 如图
![1I4PAZRR(8487@JF0YOZPA0](https://user-images.githubusercontent.com/32573416/194806891-8d7a284e-48c9-4985-b2e2-84e79a560891.png)

**Comment by yoyo837** [comment]
fixed in #561
