### ISSUE TITLE
beforeUpload返回图片压缩后的Blob对象时，依然使用原file对象

### ISSUE THREAD

**Issue by purelanren** [react-component/upload#48]
upload时有判断必须是file对象，可不可以加上Blob对象的判断

**Comment by shepherdwind** [comment]
具体场景是什么？你是在前端对图片进行压缩么？有 demo 例子，我跑一下看看

**Comment by purelanren** [comment]
是的，在前端对图片进行了压缩。使用的是下面这个压缩工具：
[https://github.com/think2011/localResizeIMG](url)

场景如下：
我在beforeUpload方法中压缩图片，然后返回压缩后的blob对象
但AjaxUploader.js中upload方法对返回的对象做了判断：

      before.then((processedFile) => {
        if (Object.prototype.toString.call(processedFile) === '[object File]') {
          this.post(processedFile);
        } else {
          this.post(file);
        }
      })

但是此时 processedFile的类型为`[object Blob]`，所以还是使用了原来未压缩的file对象

另：
blob对象不存在文件名称，request.js接收的filename其实是fieldname：
`formData.append(option.filename, option.file)`
可不可以增加filename的参数：
`formData.append(option.fieldname, option.file, option.filename)`

thx

**Comment by benjycui** [comment]
其实不是很能理解为什么要做这么一个判断：

```js
Object.prototype.toString.call(processedFile) === '[object File]'
```

觉得只要开发者保证处理后的文件是可以发到服务器的就可以了？

ref：https://github.com/react-component/upload/commit/9fe82a6d7bc3b6bff513b54cd53efba479c0f468

**Comment by shepherdwind** [comment]
https://github.com/react-component/upload/pull/41#r66920567

> 确保 resolve 传递过来的是 File 对象

@purelanren 你这种场景，加一个 Blob 判断就好了，发一个 mr 呗，改起来应该很简单，参考 https://github.com/react-component/upload/pull/41 这个好了

**Comment by purelanren** [comment]
那么是否可以增加filename的参数，让前端处理Blob对象的文件名称？

**Comment by shepherdwind** [comment]
不是很明白什么意思，filename 参数从 file 对象不就可以拿到吗？

**Comment by purelanren** [comment]
原file对象是可以拿到filename，可是blob对象是没有文件名称的，因此request.js的formdata传递的对象是没有文件名的：

`formData.append(fieldname, blob)`

如果可以接收filename参数就可以解决这个问题：

`formData.append(fieldname, blob, filename)`

**Comment by shepherdwind** [comment]
额，这个在 beforeUpload 的时候，还拿不到 formData 。blob 增加一个 filename 属性可以不？

**Comment by purelanren** [comment]
blob是只读的对象，其实可以在后端处理，不过想更灵活一点

**Comment by shepherdwind** [comment]
这个你可以自己记录一下 filename ，然后通过 data 参数传递一个函数，然后把 filename 再传回去，mr 合了。

**Comment by shepherdwind** [comment]
2.1.1 发了
