### ISSUE TITLE
较大的文件上传中的时候想要取消上传有什么方法吗？

### ISSUE THREAD

**Issue by angelsouloo** [react-component/upload#49]
看到内部有提供abort方法，但在外面取不到

**Comment by angelsouloo** [comment]
忘了说明了，不是调用组件的删除按钮，而是在其他地方手动删除

**Comment by afc163** [comment]
http://react-component.github.io/upload/examples/simple.html

用 ref 去取。

**Comment by angelsouloo** [comment]
Warning: Stateless function components cannot be given refs (See ref "inner" in UploadDragger created by DataSource). Attempts to access this ref will fail
我使用的是1.7.0版antd里的upload组件的Dragger，是不是必须升级到较新的版本啊

**Comment by afc163** [comment]
看 changelog。

**Comment by ShadowWalker627** [comment]
https://juejin.im/post/5e984a87e51d4546f27ffca5#heading-6
