### ISSUE TITLE
4.3.6版本 更改了内部的 click 事件导致生产报错了 

### ISSUE THREAD

**Issue by eternallycyf** [react-component/upload#532]
<img width="1365" alt="截屏2023-12-25 19 59 37" src="https://github.com/react-component/upload/assets/63464198/440602f2-db59-4997-ba82-e86ba8abd67d">
- 项目锁定了antd版本 但是antd子依赖 rc-upload:~4.3.0 

- 代码中使用了 UploadRef.current.upload.uploader.onClick() 实现替换文件等功能
- rc-upload 更新后 onClick内部使用了 e.target变量 导致报错了 需要判断下空值
- 现生产代码使用 UploadRef.current.upload.uploader.onClick({target: undefined}) 暂时修复

**Comment by zombieJ** [comment]
不要调用内部接口，要找 HTML 元素外部 ref 后通过 querySelector input 去取。
