### ISSUE TITLE
跨域ajax请求,遇到的问题

### ISSUE THREAD

**Issue by Grifree** [react-component/upload#54]
![](http://free01.b0.upaiyun.com/image/1476787001.png)

**Comment by benjycui** [comment]
这种问题跟没问没两样。

**Comment by Grifree** [comment]
不好意思 orz , 此图 我设置的是post , 跨域请求ajax , 但是首次会发送一个ajax的request method为options , 进行尝试发送 , 此次发送是不带request payload的数据 , 但是状态200后. 依旧没有再次产生post方式的ajax.
那么 , 我该怎么办才能成功发送post方式的ajax呢?

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+upload+%E8%B7%A8%E5%9F%9F+is%3Aclosed
