### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by yesmeck** [react-component/upload#55]
现在 Upload 在 node 环境下渲染会用 IframeUploader，浏览器下渲染会用 AjaxUploader，导致两边渲染结果不同，做 SSR 的时候 React 会有警告。

**Comment by shepherdwind** [comment]
可以配置强制使用 AjaxUploader 的

**Comment by shepherdwind** [comment]
悲剧 😅 这个功能别改没了

**Comment by afc163** [comment]
supportServerRender

**Comment by shepherdwind** [comment]
supportServerRender 这个一定使用 AjaxUploader 的 https://github.com/react-component/upload/blob/master/src/Upload.jsx#L82

可以考虑直接关闭 supportServerRender ，这样服务端就不渲染了，就不会报错了

**Comment by shepherdwind** [comment]
我看错了， supportServerRender 原理就是服务端直接不渲染，直接用这个应该 ok
