### ISSUE TITLE
how to use props "accept"?

### ISSUE THREAD

**Issue by eternalsky** [react-component/upload#6]
Description is crude, and use not illustrated in example.

**Comment by shepherdwind** [comment]
You can get more info from  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept .

The accept just render as input accept attribute, so only support for model broswer.

**Comment by eternalsky** [comment]
ok, thanks

**Comment by yairEO** [comment]
The link above has changed. Here's a one which work:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept
