### ISSUE TITLE
cancel upload

### ISSUE THREAD

**Issue by xxShawn** [react-component/upload#62]
how to cancel upload
this.refs.inner.abort is not supplied

**Comment by hlindley-ccssi** [comment]
@xxShawn did you ever find a solution for this?

**Comment by paranoidjk** [comment]
@xxShawn
 what do you actually meaning when you say ` not supplied` ? Can you give us more detail info ?

You can check the demo code at here http://react-component.github.io/upload/examples/simple.html

**Comment by YashGulati** [comment]
how to cancel the whole operation in beforeUpload()  ?

**Comment by YashGulati** [comment]
found it...
      beforeUpload(file) {
        if (file.size > 10485760){
          console.log('greater than 10mb');
          return new Promise(function (resolve) {
            console.log('file size exceeds');
          });
        }
        console.log('nice file size');
      }

**Comment by benjycui** [comment]
@xxShawn close, for you cannot provide further information.
