### ISSUE TITLE
beforeUpload 中 Promise.reject 的处理

### ISSUE THREAD

**Issue by xiaodu527** [react-component/upload#64]
@shepherdwind 

你好，我在 beforeUpload中 如果抛出了Promise.reject的异常，IE和火狐等浏览器都会出现
Unhandled promise rejection的错误；

能否在源码  AjaxUploader文件里面的upload方法里面：

`if(before&&before.then) {
  before.then(...)
}
`

添加一个异常捕获处理？

`  if(before&&before.then) {  
    before.then(...).catch((err)=>{})
  }
`

**Comment by shepherdwind** [comment]
具体场景列一下，我感觉最好在 Promise 里面直接处理异常吧。不是很清楚为什么一定要在组件里面处理业务异常。

**Comment by xiaodu527** [comment]
@shepherdwind 
我要实现的功能是： 在图片上传之前对file进行压缩处理，并对选择的文件进行筛选
代码如下： 
这是 beforeUpload 函数，

![qq 20170220202301](https://cloud.githubusercontent.com/assets/16668520/23124964/9ed0ec28-f7aa-11e6-872d-8c8462311237.jpg)

我已经用 try catch进行了异常处理，并且在catch里面捕获到了异常，但是上图代码会出现下面的情况：

![qq 20170220202121](https://cloud.githubusercontent.com/assets/16668520/23125102/241e61f8-f7ab-11e6-9428-2852a3d53560.jpg)

虽然捕获到了异常，但是 还是上传了这个mp4文件；

只有在catch里面继续抛出异常才能终止这个文件的上传...不知道什么情况？

**Comment by shepherdwind** [comment]
哦，我知道了，这里处理是有问题。

**Comment by shepherdwind** [comment]
2.3.3 加了一个 catch
