### ISSUE TITLE
后端接口要返回什么样的数据

### ISSUE THREAD

**Issue by bing1021** [react-component/upload#69]
后端要返回什么样的数据啊？
刚写的代码，onChange事件发现只有uploading 状态

**Comment by yesmeck** [comment]
`Upload` 不关心返回的数据。

**Comment by bing1021** [comment]
onChange事件为什么只有uploading状态啊，没有done状态

**Comment by yesmeck** [comment]
到这里 http://new-issue.ant.design/ 提个  issue 吧，提供个在线 demo。
