### ISSUE TITLE
请教下最新版本（2.3.7）以上package.json的module字段的意义

### ISSUE THREAD

**Issue by shinyChen** [react-component/upload#76]
最新版本中（2.3.7），package.json多了一个字段："module": "./es/index"，请问是什么意思？

**Comment by tinys** [comment]
这个导致webpack 解析从module下开始找。我知道目的是为了实现es6模块引入。但是node_module下，没有配置babel解析的引入报错。请问这个问题怎么解决？

**Comment by shepherdwind** [comment]
😓感觉对webpack 有影响，那会有问题了

**Comment by shepherdwind** [comment]
@tinys 可以给以出错的例子么？我这边重试一下，如果有问题，我这还是先回滚这个 mr #75 吧

**Comment by shepherdwind** [comment]
这个 module 是为了给 rollup 用的。

**Comment by paranoidjk** [comment]
module下除了模块语法，其他和lib是一样的，不应该会有问题，最好给出例子
https://webpack.js.org/guides/author-libraries/#final-steps

**Comment by tinys** [comment]
hi，我这里构建的时候，通过source-mapping 看到的是引入了rc-upload/es下的路径。但是在antd下的引入的时候 外边多了一层default。
<img width="726" alt="source-mapping" src="https://cloud.githubusercontent.com/assets/1773326/26335457/b05e0a48-3f9e-11e7-833e-ee4b2ad931d8.png">
<img width="658" alt="upload-default" src="https://cloud.githubusercontent.com/assets/1773326/26335459/b60f5fd2-3f9e-11e7-88b4-9e31641e576b.png">

通过对webpack2 的文档我看到
https://webpack.js.org/configuration/resolve/#resolve-mainfields
在浏览器里面，默认查找index的方式是通过package.json下面的书序开始找的。
``mainFields: ["browser", "module", "main"]``
而webpack1 的时候只查找main这个字段。
通过将webpack2配置的resolve.mainFields 设置为 ["browser", "main"] 后解决

**Comment by paranoidjk** [comment]
单纯看 es 下面的代码是正常的 https://unpkg.com/rc-upload@2.3.7/es/index.js

@tinys 你所说的 **在antd下的引入的时候 外边多了一层default。** 能否提供一个demo？ 感觉是 babel-plugin-add-module-exports 的问题

**Comment by tinys** [comment]
额   我的babel loader  也没解析node_module下的内容。。

**Comment by tinys** [comment]
@paranoidjk 已经查明，这个是webpack 2.1.0-beta.27 这个版本的bug。升级到2.6.0 后不存在了
https://github.com/tinys/webpackes
以上项目是webpack 2.1.0-beta.27 这个版本下发生的错误。
