### ISSUE TITLE
在加了FormData polyfill的IE9里面会使用ajaxUploader从而导致失败

### ISSUE THREAD

**Issue by joybee007** [react-component/upload#80]
如题，
建议判断的时候改成无法模仿的File

**Comment by mboo2005** [comment]
加上polyfill ie9下直接报错。
不加polyfill，可以使用，但是返回结果后会error。追踪是这段代码有问题，因为服务器返回的是一段json，没有script，而这里      const script = doc.getElementsByTagName('script')[0];  取script，导致undefined。  怎么解决？
onLoad = () => {
    if (!this.state.uploading) {
      return;
    }
    const { props, file } = this;
    let response;
    try {
      const doc = this.getIframeDocument();
      const script = doc.getElementsByTagName('script')[0];
      if (script && script.parentNode === doc.body) {
        doc.body.removeChild(script);
      }
      response = doc.body.innerHTML;
      props.onSuccess(response, file);
    } catch (err) {
      warning(false, 'cross domain error for Upload. Maybe server should return document.domain script. see Note from https://github.com/react-component/upload');
      response = 'cross-domain';
      props.onError(err, null, file);
    }
    this.endUpload();
  }

**Comment by shepherdwind** [comment]
@joybee007 引入了什么 polyfill ？

**Comment by shepherdwind** [comment]
就加一个 native code 判断可以么，比如这样

```
typeof FormData !== 'undefined'  && FormData.toString().indexOf('[native code]') > -1
```

**Comment by joybee007** [comment]
@shepherdwind 一个模拟FormData的插件。然而并不支持文件上传。native code判断也算不是方法的方法吧。建议判断浏览器的File类，这个暂时无法模拟~所以几乎不会有人做一个这个polyfill吧。
