### ISSUE TITLE
data参数中出现双引号会出错

### ISSUE THREAD

**Issue by joybee007** [react-component/upload#81]
`for (const key in data) {
      if (data.hasOwnProperty(key)) {
        inputs.push(`<input name="${key}" value="${data[key]}"/>`);
      }
    }`
源代码中这里用拼字符串的方式插入表单节点，如果data[key]中有双引号，会造成值设置失败。
建议改成createElement之后设置value的方式插入节点。

**Comment by benjycui** [comment]
PR is welcomed.
