### ISSUE TITLE
Why not return response's header

### ISSUE THREAD

**Issue by xiangkaiy** [react-component/upload#84]
In some case, the user need to get some information from the response header in OnSuccess callback.
Why not add this?

**Comment by paranoidjk** [comment]
https://github.com/react-component/upload/blob/e960a3fc2b6c2a6d1897ab3c89b1fce72e259ed5/src/request.js#L67

@shepherdwind 把原始的 xhr object 作为第二个参数抛出来？

**Comment by shepherdwind** [comment]
为啥要 header ，最好发一个 pr 吧。谁需要谁 pr 比较好 😄

**Comment by xiangkaiy** [comment]
In some case, such as Aliyun OSS service, will return some etag information in the header.
