### ISSUE TITLE
iOS拍摄的照片上传后出现逆时针90度旋转

### ISSUE THREAD

**Issue by walking11** [react-component/upload#86]
rt，能否根据图片exif-orientation属性进行相应的图片旋转，保持图片的正常显示

**Comment by shepherdwind** [comment]
这个组件只是做上传，图片选装这个应该在服务器处理比较好。

**Comment by walking11** [comment]
@shepherdwind 服务器处理的话上传成功后打开图片能正常展示，但第一次选择完图片预览的时候用的是本地图片，图片显示还是不正常

**Comment by paranoidjk** [comment]
antd-mobile ImagePicker 在前端显示的时候处理了一下图片方向 https://github.com/ant-design/ant-design-mobile/pull/954
