### ISSUE TITLE
IE9,  couldn't  limit the file size

### ISSUE THREAD

**Issue by czhaoli** [react-component/upload#87]
https://github.com/react-component/upload/blob/master/src/IframeUploader.jsx
Line 64 : 
  onChange = () => {
    const target = this.getFormInputNode();
    // ie8/9 don't support FileList Object
    // http://stackoverflow.com/questions/12830058/ie8-input-type-file-get-files
    const file = this.file = {
      uid: getUid(),
      name: target.value,
    };

so, beforeUpload can't get file size

**Comment by benjycui** [comment]
![image](https://user-images.githubusercontent.com/3580607/31378374-a88ce650-ad70-11e7-8ab3-0e71e76d3aba.png)
