### ISSUE TITLE
reqs[uid].abort is not a function

### ISSUE THREAD

**Issue by damonare** [react-component/upload#89]
触发场景: 使用自定义上传事件customRequest，当用户点击上传列表的取消按钮的时候报错：
```
reqs[uid].abort is not a function
```
更改AjaxUploader.jsx组件中
[判断](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx#L157)为
```javascript
if (reqs[uid].abort) {
    reqs[uid].abort();
    delete reqs[uid];
}
```
修复

**Comment by benjycui** [comment]
麻烦提供重现 demo

**Comment by afc163** [comment]
https://github.com/react-component/upload/pull/74
