### ISSUE TITLE
怎么改请求的方法为PUT ？

### ISSUE THREAD

**Issue by JackZong** [react-component/upload#95]
最近用antd Upload组件上传文件时，发现组件默认的是使用POST方法，且没有办法改，请问是否支持PUT上传文件？不支持是否有什么方案解决？谢谢

**Comment by shepherdwind** [comment]
https://github.com/react-component/upload/blob/c00f1bc9d1330dcca9c5be6af0a99bdbb669fc34/src/request.js#L71-L73

要改的花得加一个配置项了。

**Comment by yesmeck** [comment]
`customRequest`?

**Comment by JackZong** [comment]
@yesmeck 对的 不知道customRequest怎么写可以查看源码的request

**Comment by reanimatter** [comment]
There is quite a lot of going on in the default request implementation. Copy/pasting the entire file just to change the method seems to be overkill. It would be really nice to have it exposed at the component level.

**Comment by wx1993** [comment]
`const uploadProps = {
      name: 'file',
      showUploadList: false,
      multiple: false,
      accept: '.png, .jpg, .jpeg, .gif',
      action: url,
      beforeUpload: that.beforeUpload,
      // 这里需要指定文件上传的content-type
      headers: {
        'Content-Type': 'application/octet-stream',
      },
      // 自定文件上传的方法，覆盖组件的 onChange 方法，可以定义上传不同阶段的行为（由 axios 默认提供）
      onStart(file) {
        console.log('onStart', file, file.name);
      },
      onSuccess(ret, file) {
        console.log('onSuccess', ret, file);
        that.props.getData(key);
      },
      onProgress({ percent }, file) {
        console.log('onProgress', `${percent}%`, file.name);
      },
      onError(err) {
        console.log('onError', err);
      },
      customRequest({
        action,
        file,
        headers,
        onError,
        onProgress,
        onSuccess,
        withCredentials,
      }) {
        // 使用 FileReader 将上传的文件转换成二进制流，满足 'application/octet-stream' 格式的要求
        const reader = new FileReader();
        reader.readAsArrayBuffer(file);
        let fileData = null;
        reader.onload = (e) => {
          // 在文件读取结束后执行的操作
          fileData = e.target.result;
          // 使用 axios 进行文件上传的请求
          axios.put(action, fileData, {
            withCredentials,
            headers,
            onUploadProgress: ({ total, loaded }) => {
              // 进行上传进度输出，更加直观
              onProgress({ percent: Math.round(loaded / total * 100).toFixed(2) }, file);
            },
          }).then(response => {
              onSuccess(response, file);
            })
            .catch(onError);
        };
        return {
          abort() {
            console.log('upload progress is aborted.');
          },
        };
      },
    };
    return (
      <div>
        <Upload {...uploadProps}>
          { imageUrl ? <img src={imageUrl} /> : <Icon type='plus' /> }
        </Upload>
      </div>
    );`

**Comment by wx1993** [comment]
```js
const uploadProps = {
      name: 'file',
      showUploadList: false,
      multiple: false,
      accept: '.png, .jpg, .jpeg, .gif',
      action: url,
      beforeUpload: that.beforeUpload,
      // 这里需要指定文件上传的content-type
      headers: {
        'Content-Type': 'application/octet-stream',
      },
      // 自定文件上传的方法，覆盖组件的 onChange 方法，可以定义上传不同阶段的行为（由 axios 默认提供）
      onStart(file) {
        console.log('onStart', file, file.name);
      },
      onSuccess(ret, file) {
        console.log('onSuccess', ret, file);
        that.props.getData(key);
      },
      onProgress({ percent }, file) {
        console.log('onProgress', `${percent}%`, file.name);
      },
      onError(err) {
        console.log('onError', err);
      },
      customRequest({
        action,
        file,
        headers,
        onError,
        onProgress,
        onSuccess,
        withCredentials,
      }) {
        // 使用 FileReader 将上传的文件转换成二进制流，满足 'application/octet-stream' 格式的要求
        const reader = new FileReader();
        reader.readAsArrayBuffer(file);
        let fileData = null;
        reader.onload = (e) => {
          // 在文件读取结束后执行的操作
          fileData = e.target.result;
          // 使用 axios 进行文件上传的请求
          axios.put(action, fileData, {
            withCredentials,
            headers,
            onUploadProgress: ({ total, loaded }) => {
              // 进行上传进度输出，更加直观
              onProgress({ percent: Math.round(loaded / total * 100).toFixed(2) }, file);
            },
          }).then(response => {
              onSuccess(response, file);
            })
            .catch(onError);
        };
        return {
          abort() {
            console.log('upload progress is aborted.');
          },
        };
      },
    };
    return (
      <div>
        <Upload {...uploadProps}>
          { imageUrl ? <img src={imageUrl} /> : <Icon type='plus' /> }
        </Upload>
      </div>
    );
```
