### ISSUE TITLE
不能上传xls文件

### ISSUE THREAD

**Issue by czhaoli** [react-component/upload#96]
`
因为你用了
    if (!attrAccept(file, accept)) {
      return;
    }
导致accept为application/vnd.ms-excel，不能上传xls文件
`

**Comment by yesmeck** [comment]
设置 accept。

**Comment by czhaoli** [comment]
` 
设置了accept: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel",
可以上传xlsx，但是不可以上传xls，
我只能把降低版本才能正常上传xls文件
`

**Comment by yesmeck** [comment]
> 我只能把降低版本才能正常上传xls文件

哪个版本可以上传？

**Comment by czhaoli** [comment]
`2.4.0就可以，因为2.4.1作者用了
[import attrAccept from 'attr-accept';
...
    if (!attrAccept(file, accept)) {
      return;
    }](https://github.com/react-component/upload/blob/c00f1bc9d1330dcca9c5be6af0a99bdbb669fc34/src/AjaxUploader.jsx#L117)
而attr-accept源码
[用file.type和accept的type做比较](https://github.com/okonet/attr-accept/blob/2847ab8c065ee41092f012c8a5b61e84263c815f/src/index.js#L21)
而.xls文件拿到的name.type是""空字符串，所以和accept对比后返回false
`

**Comment by czhaoli** [comment]
2.4.0就可以，因为2.4.1作者用了 
[import attrAccept from 'attr-accept'; ... if (!attrAccept(file, accept)) { return; }](https://github.com/react-component/upload/blob/c00f1bc9d1330dcca9c5be6af0a99bdbb669fc34/src/AjaxUploader.jsx#L117) 而attr-accept源码 [用file.type和accept的type做比较](https://github.com/okonet/attr-accept/blob/2847ab8c065ee41092f012c8a5b61e84263c815f/src/index.js#L21) 而.xls文件拿到的name.type是""空字符串，所以和accept对比后返回false

**Comment by yesmeck** [comment]
chrome 的 bug https://bugs.chromium.org/p/chromium/issues/detail?id=155455

**Comment by yesmeck** [comment]
自己先在 beforeUpload 里用扩展名判断下吧。

**Comment by czhaoli** [comment]
https://github.com/react-component/upload/blob/c00f1bc9d1330dcca9c5be6af0a99bdbb669fc34/src/IframeUploader.jsx#L147
阿里云oss上传要求file在其他上传条目的最后面，而你这个file在上传条目最前面。
这个上传.xls文件的问题，我只能把你的代码拷贝一份出来进行修改后使用了

**Comment by czhaoli** [comment]
https://github.com/react-component/upload/blob/c00f1bc9d1330dcca9c5be6af0a99bdbb669fc34/src/IframeUploader.jsx#L147
阿里云oss上传要求file在其他上传条目的最后面，而你这个file在上传条目最前面。
加上这个上传.xls文件的问题，我只能把你的代码拷贝一份出来进行修改后使用了
